<?php

namespace App\Services\CalendarEvent;

use App\Models\CalendarEvent\EventRegistration;
use App\Models\Event;
use App\Models\User;
use Illuminate\Support\Facades\DB;

class EventRegistrationService
{
    /**
     * Register user for event.
     */
    public function register(User $user, Event $event, array $data = []): EventRegistration
    {
        return DB::transaction(function () use ($user, $event, $data) {
            $registration = EventRegistration::create([
                'user_id' => $user->id,
                'event_id' => $event->id,
                'notes' => $data['notes'] ?? null,
                'status' => 'registered', // auto-approved
            ]);

            // QR code auto-generated by model boot method

            // TODO: Send confirmation email with QR code

            return $registration;
        });
    }

    /**
     * Cancel registration.
     */
    public function cancel(EventRegistration $registration): bool
    {
        if (! $registration->isRegistered()) {
            throw new \Exception('Hanya registrasi dengan status registered yang bisa dibatalkan.');
        }

        $registration->update(['status' => 'cancelled']);

        return true;
    }

    /**
     * Mark attendance using QR code or registration object.
     */
    public function markAttendance(EventRegistration|string $registrationOrCode, ?int $adminId = null, ?string $notes = null): bool|EventRegistration
    {
        // If string is passed, it's an attendance code - find the registration
        if (is_string($registrationOrCode)) {
            $registration = EventRegistration::where('attendance_code', $registrationOrCode)
                ->where('status', 'registered')
                ->firstOrFail();
        } else {
            $registration = $registrationOrCode;
        }

        $data = [
            'status' => 'attended',
            'attended_at' => now(),
        ];
        
        if ($adminId) {
            $data['attended_by'] = $adminId;
        }
        
        if ($notes) {
            $data['attendance_notes'] = $notes;
        }
        
        $registration->update($data);

        // TODO: Send attendance confirmation

        return is_string($registrationOrCode) ? $registration : true;
    }

    /**
     * Get user registrations.
     */
    public function getUserRegistrations(User $user)
    {
        return EventRegistration::with('event')
            ->where('user_id', $user->id)
            ->latest()
            ->paginate(10);
    }

    /**
     * Check if user already registered for event.
     */
    public function isAlreadyRegistered(User $user, Event $event): bool
    {
        return EventRegistration::where('user_id', $user->id)
            ->where('event_id', $event->id)
            ->exists();
    }

    /**
     * Get event statistics.
     */
    public function getEventStatistics(Event $event): array
    {
        $registrations = EventRegistration::where('event_id', $event->id);

        return [
            'total' => $registrations->count(),
            'registered' => $registrations->clone()->registered()->count(),
            'attended' => $registrations->clone()->attended()->count(),
            'cancelled' => $registrations->clone()->cancelled()->count(),
            'attendance_rate' => $this->calculateAttendanceRate($event),
        ];
    }

    /**
     * Calculate attendance rate.
     */
    private function calculateAttendanceRate(Event $event): float
    {
        $total = EventRegistration::where('event_id', $event->id)->count();
        if ($total === 0) {
            return 0;
        }

        $attended = EventRegistration::where('event_id', $event->id)
            ->attended()
            ->count();

        return round(($attended / $total) * 100, 2);
    }
}
